version: '3.2'
services:
  backend1:
      build: ./backend
      tty: true
      volumes:
        - './backend/src:/var/www/html/'

  backend2:
      build: ./backend
      tty: true
      volumes:
        - './backend/src:/var/www/html/'

  backend3:
      build: ./backend
      tty: true
      volumes:
        - './backend/src:/var/www/html/'

  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - backend1
          - backend2
          - backend3
      ports:
          - '80:80'

volumes:
  backend:
